[package]
name = "ase2"
version = "0.1.0"
authors = ["Kazushi Kondo <kkkazu@g.ecc.u-tokyo.ac.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
